export
  const mySkills = [
    {
      frontEnd: [
        { title: "React.Js", icon: "/react.svg", id: 0 },
        { title: "React-Native", icon: "/android.svg", id: 1 },
        { title: "Next.Js", icon: "/nextjs.svg", id: 2 },
        { title: "SASS", icon: "/sass.svg", id: 3 },
        { title: "Styled-Components", icon: "/styled-components.svg", id: 4 },
        { title: "Jest", icon: "/jest.svg", id: 5 },
        { title: "HTML", icon: "/html5.svg", id: 6 },
        { title: "CSS", icon: "/css3.svg", id: 7 },
        { title: "Javascript", icon: "/javascript.svg", id: 8 },
        { title: "Typescript", icon: "/typescript.svg", id: 9 },
        { title: "Redux", icon: "/redux.svg", id: 10 },
      ],
      backEnd: [
        { title: "Python", icon: "", id: 0 },
        { title: "Node.Js", icon: "", id: 1 },
        { title: "Express", icon: "", id: 2 },
        { title: "Nest.Js", icon: "", id: 3 },
        { title: "Django", icon: "", id: 4 },
        { title: "Flask", icon: "", id: 5 },
        { title: "PostgreSQL", icon: "", id: 7 },
        { title: "Firebase", icon: "", id: 6 },
        { title: "MongoDB", icon: "", id: 8 },
        { title: "MySQL", icon: "", id: 9 },
      ],
      softSkills: [
        { title: "Teamwork", icon: "", id: 0 },
        { title: "Comunicação", icon: "", id: 1 },
        { title: "Resolutor", icon: "", id: 2 },
        { title: "Produtivo", icon: "", id: 3 },
        { title: "Líder", icon: "", id: 4 },
        { title: "Criativo", icon: "", id: 5 },
        { title: "Adaptável", icon: "", id: 6 },
        { title: "Ética profissional", icon: "", id: 7 },
        { title: "Resiliente", icon: "", id: 8 },
        { title: "Pensamento crítico", icon: "", id: 9 },
      ],
      others: [
        { title: "Git", icon: "", id: 0 },
        { title: "Ubuntu", icon: "", id: 1 },
        { title: "CI/CD", icon: "", id: 2 },
        { title: "Scrum", icon: "", id: 3 },
        { title: "Kanban", icon: "", id: 4 },
        { title: "DevOps", icon: "", id: 5 },
        { title: "Vercel", icon: "", id: 6 },
        { title: "Azure", icon: "", id: 7 },
        { title: "AWS", icon: "", id: 8 },
        { title: "Google Cloud / Console", icon: "", id: 9 },
      ],
    },
  ];