export const mySkills = [
  {
    frontEnd: [
      { title: "React.Js", icon: "/react.svg", id: 0 },
      { title: "React-Native", icon: "/android.svg", id: 1 },
      { title: "Next.Js", icon: "/nextjs.svg", id: 2 },
      { title: "SASS", icon: "/sass.svg", id: 3 },
      { title: "Styled-Components", icon: "/styled-components.svg", id: 4 },
      { title: "Jest", icon: "/jest.svg", id: 5 },
      { title: "HTML", icon: "/html5.svg", id: 6 },
      { title: "CSS", icon: "/css3.svg", id: 7 },
      { title: "Javascript", icon: "/javascript.svg", id: 8 },
      { title: "Typescript", icon: "/typescript.svg", id: 9 },
      { title: "Redux", icon: "/redux.svg", id: 10 },
    ],
    backEnd: [
      { title: "Python", icon: "/python.svg", id: 10 },
      { title: "Node.Js", icon: "/nodejs.svg", id: 11 },
      { title: "Express", icon: "/express.svg", id: 12 },
      { title: "Nest.Js", icon: "/nestjs.svg", id: 13 },
      { title: "Django", icon: "/django.svg", id: 14 },
      { title: "Flask", icon: "/flask.svg", id: 15 },
      { title: "PostgreSQL", icon: "/postgresql.svg", id: 17 },
      { title: "Firebase", icon: "/firebase.svg", id: 16 },
      { title: "MongoDB", icon: "/mongodb.svg", id: 18 },
      { title: "MySQL", icon: "/mysql.svg", id: 19 },
    ],
    softSkills: [
      { title: "Teamwork", icon: "/teamWork.svg", id: 20 },
      { title: "Self-manageable", icon: "/communication.svg", id: 21 },
      { title: "Troubleshooter", icon: "/troubleshooter.svg", id: 22 },
      { title: "Productive", icon: "/productive.svg", id: 23 },
      { title: "Leader", icon: "/leadership.svg", id: 24 },
      { title: "Creative", icon: "/creative.svg", id: 25 },
      { title: "Communicative", icon: "/talk.svg", id: 26 },
      { title: "Professional ethics", icon: "/ethic.svg", id: 27 },
      { title: "Resilient", icon: "/resilience.svg", id: 28 },
      { title: "Critical thinking", icon: "/critic analytic.svg", id: 29 },
    ],
    others: [
      { title: "Git", icon: "/git.svg", id: 30 },
      { title: "Docker", icon: "/docker.svg", id: 31 },
      { title: "CI/CD", icon: "/cicd.svg", id: 32 },
      { title: "Scrum", icon: "/scrum.svg", id: 33 },
      { title: "Kanban", icon: "/scrum.svg", id: 34 },
      { title: "Ubuntu", icon: "/ubuntu.svg", id: 35 },
      { title: "Vercel", icon: "/vercel.svg", id: 36 },
      { title: "SEO", icon: "/google.svg", id: 37 },
      { title: "AWS", icon: "/amazonwebservices.svg", id: 38 },
      { title: "Google Cloud / Console", icon: "/googlecloud.svg", id: 39 },
    ],
  },
];
