import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header/Header'
import FirstSect from '../components/section01/FirstSect'
import SecondSect from '../components/section02/SecondSect'

const Home: NextPage = () => {
  return (
    <div className={'container'}>
      <Head>
        <title>Raul Henrique - Desenvolvedor Front-End</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header/>
      <FirstSect/>
      <SecondSect/>
    </div>
  )
}

export default Home
